blog/urls.py
from django.urls import path
from . import views

app_name="blog"
urlpatterns = [
   
    path('', views.blog, name='blog'),
    path('create-blog/', views.create_blog, name='create_blog'),
    path('update-blog/<int:id>/', views.update_blog, name='update_blog'),
    path('delete-blog/<int:id>/', views.delete_blog, name='delete_blog'),
    path('<int:id>/', views.blog_i, name='blog_i'),
]

main/urls.py
from django.urls import path
from . import views

app_name="main"
urlpatterns = [
    path('', views.home, name='home'),
   

    path('1', views.first, name='first'),
    path('2', views.second, name='second'),
    path('3', views.third, name='third'),
]

webone/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('blog/',include('blog.urls')),
]

blog/models.py
from unicodedata import name
from django.db import models
from sqlalchemy import false

class Blog(models.Model):
    # """Blog Post"""
    title=models.CharField(max_length=100, null=false)
    description = models.CharField(max_length=500,null=True)
    content=models.TextField()
    date =models.DateTimeField(auto_now_add=True)

class Comment(models.Model):
    #  """ comment"""
    id_blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='comments')
    name=models.CharField(max_length=100, null=false)
    comment = models.CharField(max_length=500,null=false)
    date = models.DateTimeField(auto_now_add=True)
    

main/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render, redirect
from .models import Blog, Comment



# Create your views here.
def blog(request):
    blogs = Blog.objects.order_by('-date')[:5]
    param={'blogs':blogs}
    print(param)
    return render(request,'blog/blog.html',param)
    

def create_blog(request):
    if request.method == "POST":
        _title = request.POST.get('title')
        _description = request.POST.get('description')
        _content=request.POST.get('content')
        if _title =='':
            return render(request,'blog/create_blog.html', {'error_message': ' The title is not empty. '})
        else:
            blog = Blog(title =_title, description = _description,content=_content )
            blog.save()
            return redirect('blog:blog')
    else:
        return render(request,'blog/create_blog.html')

def blog_i(request, id):
    
    blog = Blog.objects.get(pk=id)
    comments = blog.comments.all().order_by('-date')[:10]
    param={'comments':comments,'blog':blog,}
    if request.method == "POST":
       
        _name = request.POST.get('your_name')
        _comment=request.POST.get('comment')
        
        if _name =='' or _comment=='':
            return render(request,'blog/blog_i.html',{'error_message': ' The \"Your name\" or \"comment\" is not empty. '},param)
        else:
            comment_new = Comment(id_blog=blog, name = _name, comment = _comment)
            comment_new.save()
            return render(request,'blog/blog_i.html',param)
    return render(request,'blog/blog_i.html',param)

def update_blog(request,id):
    if request.method == "POST":
        _title = request.POST.get('title')
        _description = request.POST.get('description')
        _content=request.POST.get('content')
        if _title =='':
            return render(request,'blog/update_blog.html', {'error_message': ' The title is not empty. '})
        else:
            blog = Blog.objects.get(pk=id)
            blog.title=_title
            blog.description=_description
            blog.content=_content
            blog.save()
            blog_id= Blog.objects.get(pk=id)
            new_blog={'blog':blog_id}
            return render(request,'blog/blog_i.html',new_blog)
    else:
        return render(request,'blog/update_blog.html')

def delete_blog(request,id):
    blog=Blog.objects.filter(pk=id).delete()
    return redirect('blog:blog')

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse


def home(request):
    return render(request, 'main/home.html')
   

def first(request):
    return render(request,'main/first.html')
def second(request):
    return render(request,'main/second.html')
def third(request):
    return render(request,'main/third.html')

blog/templates/blog/blog.html
{% extends 'main/base.html' %}
{% block title %} Home {% endblock %}

{% block head %}
{% load static %}
<style>
    div.blog_body {
        width: 100%;
        height: 100%;
        display: flex;
    }

    div.dropdown {
        padding: 2% 0%;
        background-color: #EFEFEF;
    }

    .dropdown:hover {
        background-color: white;
        height: 100%;
    }

    .dropbtn {

        color: black;
        height: 100%;
        width: 100%;
        font-size: 100%;
        border: none;
        cursor: pointer;
    }


    .dropdown-content {
        display: none;
        position: absolute;
        background-color: #f9f9f9;
        min-width: 100px;
        box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);
        z-index: 1;
    }

    .dropdown-content a {
        color: black;
        padding: 12px 16px;
        text-decoration: none;
        display: block;
    }

    .dropdown-content a:hover {
        background-color: #f1f1f1
    }

    .dropdown:hover .dropdown-content {
        display: block;
    }

    .blog_menu {
        display: flex;
        flex-direction: row-reverse;
        width: 100%;
    }

    div.blog_side {
        width: 30%;
    }


    div.blog_mid {
        
        text-align: left;
        width: 40%;
        display: flex;
        flex-direction: column;
    }

    .blog_title {
        font-size: 250%;
        /* color: #34495e; */
    }
    .blog_title a{
        color: #34495e;
    }
    .blog_title p{
        font-size: 50%;
        color: black;
    }
    .blog_description{
        font-size: 150%;
    }
    .blog_item{
        padding: 2% 0%;
        
    }
    /*  mobile and tablet */
@media only screen  and (max-width:1024px) {
   
}
  /* Mobile width <740px */
  @media only screen and (max-width:740px) {
    div.blog_side {
        width: 1%;
    }


    div.blog_mid {
        text-align: center;
        width: 98%;
    }
}

/* tablet width >=740px and width< 1024 */
@media only screen and (min-width:741px) and (max-width:1024px) {
    div.blog_side {
        width: 10%;
    }


    div.blog_mid {
        text-align: center;
        width: 80%;
    }
}
</style>
<div class="blog_menu">
    <div class="dropdown">
        <div><button class="dropbtn">Blog Manager</button></div>
        <div class="dropdown-content">
            <a href="{% url 'blog:create_blog' %}">Add Blog</a>
        </div>
    </div>
</div>
{%endblock%}
{% block body %}
<div class="blog_body">
    <div class="blog_side"></div>
    <div class="blog_mid">

        {% for blog in blogs %}
        <div class="blog_item">
            <div class="blog_title"><a href="{% url 'blog:blog_i' blog.id %}">
                    <p>{{blog.id}}</p><h1>{{blog.title}}</h1>
                </a>
            </div>
            <div class="blog_description"><br>{{blog.description}} </div>
            <div class="blog_date"><br>{{blog.date}}</div>
        </div>
        {% endfor %}

    </div>
    <div class="blog_side"></div>

</div>



{%endblock%}

blog/templates/blog/blog_i.html
{% extends 'main/base.html' %}
{% block title %} Home {% endblock %}

{% block head %}
{% load static %}
<style>
    .header_4 {
        display: flex;
        flex-direction: row-reverse;
        width: 73%;
    }

    div.dropdown {
        padding: 2% 0%;
        background-color: #EFEFEF;
    }

    .dropdown:hover {
        background-color: white;
        height: 100%;
    }

    .dropbtn {

        color: black;
        height: 100%;
        width: 100%;
        font-size: 100%;
        border: none;
        cursor: pointer;
    }


    .dropdown-content {
        display: none;
        position: absolute;
        background-color: #f9f9f9;
        min-width: 100px;
        box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);
        z-index: 1;
    }

    .dropdown-content a {
        color: black;
        padding: 12px 16px;
        text-decoration: none;
        display: block;
    }

    .dropdown-content a:hover {
        background-color: #f1f1f1
    }

    .dropdown:hover .dropdown-content {
        display: block;
    }

    .blogi_body {
        width: 100%;
        height: 100%;
        display: flex;
    }

    .blogi_side {
        width: 20%;
    }

    .blogi_mid {
        width: 60%;
        flex-direction: column;
    }

    .blogi_add_comment {
        text-align: left;
    }

    .blogi_mid h1 {
        font-size: 250%;
    }
    .blogi_comment{
        border-radius:5px;
        background-color: #EEEEEE;
    }
    .blogi_comments h1{
        color: #2e98ff ;
        font-size: 120%;
    }

    /*  mobile and tablet */
    @media only screen and (max-width:1024px) {}

    /* Mobile width <740px */
    @media only screen and (max-width:740px) {
        .blogi_side {
            width: 1%;
        }

        .blogi_mid {
            width: 98%;
        }

        .blogi_add_comment {
            text-align: center;
        }
    }

    /* tablet width >=740px and width< 1024 */
    @media only screen and (min-width:741px) and (max-width:1024px) {
        .blogi_side {
            width: 10%;
        }

        .blogi_mid {
            width: 80%;
        }

        .blogi_add_comment {
            text-align: center;
        }


    }
</style>
<div class="header_4">
    <div class="dropdown">
        <div><button class="dropbtn">Blog Manager</button></div>
        <div class="dropdown-content">
            <a href="{% url 'blog:create_blog' %}">Add Blog</a>
            <a href="{% url 'blog:update_blog' blog.id %}">Edit Blog</a>
            <a href="{% url 'blog:delete_blog' blog.id %}">Delete Blog</a>
        </div>
    </div>

</div>
{%endblock%}
{% block body %}
<div class="blogi_body">
    <div class="blogi_side"></div>
    <div class="blogi_mid">
        <div>
            <p>{{blog.id}}</p>
            <h1> {{blog.title}}</h1>
            <h3><br>{{blog.description}}</h3>
            <p> <br>{{blog.content}} <br></p>
        </div>

        <div class="blogi_comments">
            {% for comment in comments %}
            <br>
                <div class="blogi_comment">
                    <h1>{{comment.name}}</h1>
                    <p>{{comment.comment}}</p>
                    
                </div>
                
            {% endfor %}
        </div>

        <div class="blogi_add_comment">
            <h1><br> Leave a comment:</h1>
            <form method="POST">
                {% if error_message %}
                <span class="alert">{{error_message}}</span>
                <br>
                {% endif %}
                {% csrf_token %}
                <input type="text" name="your_name" placeholder="Your name">
                <br><br>
                <textarea type="text" rows="10" cols="30" name="comment" placeholder="Leave a comment"></textarea>
                <br><br>
                <input class="submit" type="submit" name="submit" value="Save">
            </form>
        </div>
    </div>
    <div class="blogi_side"></div>
</div>
{%endblock%}

blog/templates/blog/create_blog.html
{% extends 'main/base.html' %}
{% block title %} Home {% endblock %}

{% block body %}
{% load static %}
<style>
  .blogi_title{
    text-align: center;
    font-size: 150%;
  }
  .addblock_body{
    width: 100%;
    height: 100%;
    display: flex;
  }
  .addblock_side{
    width: 20%;
  }
  .addblock_mid{
    border: 0;
    padding: 0;
    padding: 2% 0%;
    width: 60%;
    text-align: center;
  }
  .addblock_mid textarea{
    width: 100%;

  }
  /*  mobile and tablet */
@media only screen  and (max-width:1024px) {
  .addblock_side{
    width: 1%;
  }
  .addblock_mid{
    padding: 2% 0%;
    width: 98%;
    text-align: center;
  }
}
  /* Mobile width <740px */
  @media only screen and (max-width:740px) {
}

/* tablet width >=740px and width< 1024 */
@media only screen and (min-width:741px) and (max-width:1024px) {
}
</style>
<div class="blogi_title"><h1>Add blog</h1></div>
<div class="addblock_body"> 
  <div class="addblock_side"></div>
  <div class="addblock_mid">
<form method="POST" >
    {% if error_message %}
    <span class="alert">{{error_message}}</span>
    <br>
    {% endif %}
    {% csrf_token %}
    <input type="text" name="title" placeholder="title">
    <br><br>
    <textarea type="text" rows="10" name="description" placeholder="description"></textarea>
    <br><br>
    <textarea  type="text" rows="30" name="content" placeholder="content"></textarea>
    <br><br>
    <input class="submit" type="submit" name="submit" value="POST">
  </form>
</div>
  <div class="addblock_side"></div>
</div>
{%endblock%}

blog/templates/blog/update_blog.html
{% extends 'main/base.html' %}
{% block title %} Home {% endblock %}

{% block body %}
{% load static %}
<style>
  .blogi_title{
    text-align: center;
    font-size: 150%;
  }
  .addblock_body{
    width: 100%;
    height: 100%;
    display: flex;
  }
  .addblock_side{
    width: 20%;
  }
  .addblock_mid{
    padding: 2% 0%;
    width: 60%;
    text-align: center;
  }
  .addblock_mid textarea{
    width: 100%;

  }
  /*  mobile and tablet */
@media only screen  and (max-width:1024px) {
  .addblock_side{
    width: 1%;
  }
  .addblock_mid{
    padding: 2% 0%;
    width: 98%;
    text-align: center;
  }
}
  /* Mobile width <740px */
  @media only screen and (max-width:740px) {
}

/* tablet width >=740px and width< 1024 */
@media only screen and (min-width:741px) and (max-width:1024px) {
}
</style>
<div class="blogi_title"><h1>Update blog</h1></div>
<div class="addblock_body"> 
  <div class="addblock_side"></div>
  <div class="addblock_mid">
<form method="POST" >
    {% if error_message %}
    <span class="alert">{{error_message}}</span>
    <br>
    {% endif %}
    {% csrf_token %}
    <input type="text" name="title" placeholder="title">
    <br><br>
    <textarea type="text" rows="10" name="description" placeholder="description"></textarea>
    <br><br>
    <textarea  type="text" rows="30" name="content" placeholder="content"></textarea>
    <br><br>
    <input class="submit" type="submit" name="submit" value="SAVE">
  </form>
</div>
  <div class="addblock_side"></div>
</div>
  </form>
{%endblock%}

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <style>
        a {
            color: black;
            text-decoration-line: none;
        }

        .header {
            width: 100%;
            height: 20%;
            display: flex;
            background-color: beige;
        }

        .header_title {
            padding: 1% 0% 1% 5%;
            width: 17%;
            height: 100%;
            font-size: 250%;
            font-weight: bolder;
        }

        div.header_item {
            padding: 1% 0% 1% 0%;
            font-size: 150%;
            width: 5%;
            height: 100%;
            text-align: center;
            vertical-align: bottom;

        }

        div.header_item:hover {
            background-color: #A9A9A9;
        }

        .body {
            width: 100%;
            height: 100%;

        }

        .header_menu {
            display: flex;
            flex-direction: row-reverse;
            width: 73%;
            
        }

        div.login {
            padding: 2% 0%;
        }
        /* Mobile width <740px */
        @media only screen and (max-width:740px) {
        .header_title {
        width: 40%;
        }
        div.header_item {
            width: 20%;
        }
        .header_menu{
            width: 20%;
        }

        } 
        /* tablet width >=740px and width< 1024 */
        @media only screen and (min-width:741px) and (max-width:1024px) {
        .header_title {
        width: 20%;
        font-size: 150%;
        }
        div.header_item {
            width: 10%;
        }
        .header_menu{
            width: 60%;
        }
        
        }
    </style>
</head>

<body>
    <div class="body">
        <div class="header">
            <div class="header_title">
                <a href="{% url 'main:home' %}">My Portfolio</a>
            </div>
            <div class="header_item">
                <a href="{% url 'main:home' %}">Home</a>
            </div>
            <div class="header_item">
                <a href="{% url 'blog:blog' %}">Blog</a>
            </div>
            <div class="header_menu">
                
                    {% block head %} {% endblock %}
                
            </div>
        </div>
        <div style="width: 100%; height: 100%;">{% block body %} {% endblock %}</div>
    </div>
</body>

</html>

main/templates/main/first.html
{% extends 'main/base.html' %}
{% block title %} First Project {% endblock %}

{% block body %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/project.css' %}">
<!-- <style>
div.pro_item {
    font-size: 150%;
    padding: 1% 5%;
    width: 100%;
}

div.body1 {
    height: 100%;
    width: 100%;
    display: flex;

}
.pro_img img{
    display: block;
    margin-left: auto;
    margin-right: auto;
    width: 100%;
    object-fit: cover;
}
.pro_img {
    padding: 1% 0% 0% 5%;
    width: 60%;
    height: auto;
}

.pro_alt {
    width: 40%;
    padding: 1% 0% 0% 3%;
    display: flex;
    flex-direction: column;
}

.pro_alt h1 {
    
    font-size: 200%;
}

.pro_alt p {
    font-size: 100%;
}
  /* Mobile width <740px */
  @media only screen and (max-width:740px) {
    div.body1 {
        flex-wrap: wrap
        
    }
    .pro_img {
        max-width: 90%;
        height: auto;
}
.pro_alt {
    width: 100%;
    padding: 1% 0% 0% 5%;
    text-align: center;
    
}
   
}

/* tablet width >=740px and width< 1024 */
@media only screen and (min-width:741px) and (max-width:1024px) {
    div.body1 {
        flex-wrap: wrap
        
    }
    .pro_img {
        width: 90%;
        height: auto;
    }
    .pro_alt {
    
        padding: 1% 0% 0% 5%;
        
    }
}
</style> -->
<div>
    <div class="pro_item">
        <h1>My First Project</h1>
    </div>
    <div class="body1">
        <div class="pro_img">
        <img src="{% static 'img/first.jpg' %}" alt="">
        </div>
        <div class="pro_alt">
            <div>
                <h1>About the project:</h1>
                <br>
                <p>A web development project</p>
                <br>
            </div>
            <div>
                <h1>Technology used:</h1>
                <br>
                <p>Django</p>
                <br>
                <p>HTML,CSS,Javascript</p>
                <br>
                
            </div>
            <div>
                <h1>Author</h1>
                <br>
                <p>Duy Hieu</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/home.html
{% extends 'main/base.html' %}
{% block title %} Home {% endblock %}

{% block body %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/home.css' %}">
<style>
    img {
        image-rendering: pixelated;
        object-fit: fill;
    }

    .body_projects {
        width: 100%;
        height: 100%;
        display: flex;
        flex-wrap: wrap
    }

    .home_item {
        padding: 0% 0% 5% 5%;
        width: 26.6%;
        display: flex;
        flex-direction: column;

    }
    div.home_item h1 {
        padding: 3% 0% 3% 0%;
        font-size: 200%;

    }

    div.home_item h2 {

        padding: 3% 0% 3% 0%;
        font-size: 150%;

    }

    div.home_item a {
        width: 20%;
        height: 100%;
        padding: 2% 2%;
        background-color: #4267b2;
    }

    div.body_title {
        font-size: 250%;
        padding: 1% 0% 1% 5%;
        width: 100%;

    }

    div.body_title h1 {
        font-size: 250%;
        padding: 1% 0% 1% 5%;
        width: 100%;

    }

    .home_item img {
        transition: all .2s ease-in-out;
    }

    .home_item img:hover {
        transform: scale(1.1);
    }

    .home_item a {
        text-align: center;
        transition: all .2s ease-in-out;
    }

    .home_item a:hover {
        transform: scale(1.2);
    }

    .home_pro {
        font-size: 250%;
        padding: 1% 0% 1% 5%;
    }

    /* Mobile width <740px */
    @media only screen and (max-width:740px) {
        .home_item{
            width: 95%;
        }
      
    }

    /* tablet width >=740px and width< 1024 */
    @media only screen and (min-width:741px) and (max-width:1024px) {
        .home_item{
            width: 45%;
        }
        div.home_item a {
        width: 25%;
    }
    }
</style>
<div>
    <div class="home_pro">
        <h1>Projects</h1>
    </div>
    <div class="body_projects">
        <div class="home_item">
            <img width="100%" src="{% static  'img/first.jpg' %}" alt="">
            <h1>My First Project</h1>
            <h2>A web development project</h2>
            <a href="{% url 'main:first' %}">Read More</a>
        </div>
        <div class="home_item">
            <img width="100%" src="{% static  'img/second.jpg' %}" alt="">
            <h1>My Second Project</h1>
            <h2>A web development project</h2>
            <a href="{% url 'main:second' %}">Read More</a>
        </div>
        <div class="home_item">
            <img width="100%" src="{% static  'img/third.jpg' %}" alt="">
            <h1>My Third Project</h1>
            <h2>A web development project</h2>
            <a href="{% url 'main:third' %}">Read More</a>
        </div>
    </div>
</div>
{%endblock%}

main/templates/main/second.html
{% extends 'main/base.html' %}
{% block title %} Second Project {% endblock %}

{% block body %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/project.css' %}">

<div>
    <div class="pro_item">
        <h1>My Second Project</h1>
    </div>
    <div class="body1">
        <div class="pro_img">
        <img src="{% static 'img/second.jpg' %}" alt="">
        </div>
        <div class="pro_alt">
            <div>
                <h1>About the project:</h1>
                <br>
                <p>A web development project</p>
                <br>
            </div>
            <div>
                <h1>Technology used:</h1>
                <br>
                <p>Django</p>
                <br>
                <p>HTML,CSS,Javascript</p>
                <br>

            </div>
            <div>
                <h1>Author</h1>
                <br>
                <p>Duy Hieu</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/third.html
{% extends 'main/base.html' %}
{% block title %} Third Project {% endblock %}

{% block body %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/project.css' %}">
<style>

</style>
<div>
    <div class="pro_item">
        <h1>My Third Project</h1>
    </div>
    <div class="body1">
        <div class="pro_img">
        <img src="{% static 'img/third.jpg' %}" alt="">
    </div>
        <div class="pro_alt">
            <div>
                <h1>About the project:</h1>
                <br>
                <p>A web development project</p>
                <br>
            </div>
            <div>
                <h1>Technology used:</h1>
                <br>
                <p>Django</p>
                <br>
                <p>HTML,CSS,Javascript</p>
                <br>
                
            </div>
            <div>
                <h1>Author</h1>
                <br>
                <p>Duy Hieu</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}